spring:
  data:
    mongodb:
      uri: mongodb://localhost:32769
      database: StreamDB
      autoIndexCreation: true
  servlet:
    multipart:
      maxFileSize: 10000MB
      maxRequestSize: 10000MB