spring:
  data:
    mongodb:
      uri: mongodb://localhost:32782
      database: StreamDB
      autoIndexCreation: true
  servlet:
    multipart:
      maxFileSize: 10000MB
      maxRequestSize: 10000MB
  kafka:
    bootstrap-servers: localhost:9092